Feature/drupal 8 4 upgrade and refactoring
deGov/deGov pull request #33
Opened 2017-11-16 10:10 UTC by DerH4NNES

Updating Drupal to 8.4.2

2017-11-16 10:12 UTC, KeldorDE approved these changes

2017-11-16 10:40 UTC, rawroland approved these changes

2017-11-16 11:06 UTC, KeldorDE commented
PHP Fatal error:  Cannot redeclare Drupal\\entity_browser\\Plugin\\views\\display\\EntityBrowser::getOption() in /var/www/html/degov/docroot/modules/contrib/entity_browser/src/Plugin/views/display/EntityBrowser.php on line 67

2017-11-16 11:07 UTC, KeldorDE requested changes
PHP Fatal error:  Cannot redeclare Drupal\\entity_browser\\Plugin\\views\\display\\EntityBrowser::getOption() in /var/www/html/degov/docroot/modules/contrib/entity_browser/src/Plugin/views/display/EntityBrowser.php on line 67

2017-11-16 15:02 UTC, KeldorDE approved these changes

2017-11-17 10:13 UTC, rawroland approved these changes

2017-11-17 10:13 UTC, merged